import random
random_no=random.randint(1,100)
print("\n**Rule: Here one number generated by stystem and by your luck choose that number.**")
number=int(input("\nEnter any number 1 to 100:"))
game_over=0
attempt=1
while  not game_over:
 if random_no==number:
  print(f"Congrats finally you choose select no and your total attempt:{ attempt}")
  game_over=1
 else:
  if random_no<number:
    print("Too High")
  else:
   print("Too Less")
   
 number=int(input("Again try:"))
 attempt=attempt+1
 
  
  